graph LR
    developer --> Network
    Network --> repos
    repos --> git
    Network --> Osi
    Network --> Blog
    Blog --> Sew
    Osi --> Pom
    Osi --> OsiLib(lib)
    Pom --> Dem
    Dem --> Gel
    Gel --> Sep
    Sep --> Worker
    Worker --> Sew
    Sep --> Cin
    Cin --> Sew
    Sew --> splitcells.net
    Sew --> logs
    logs --> Sew
    splitcells.net --> user