#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
command_managed_id='69741576422382621825387143332053926495'
	. command.managed.define
. this.requires snap
sudo snap install $1 # You can search for packages at "https://snapcraft.io/store".
