# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
# SPDX-FileCopyrightText: Contributors To The `net.splitcells.*` Projects
on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: ubuntu:latest
        # This is required, because playwright does not work in `alpine:latest`.
        # Maybe this could be fixed via `playwright.driver.tmpdir`. See https://github.com/microsoft/playwright-java/issues/728
    steps:
      - name: Setup Build
        run: |
          apt update --fix-missing # $(pwd) = /workspace/splitcells-net/net.splitcells.network and --fix-missing is required on Codeberg. 
          apt install -y bash curl git python3 openjdk-21-jdk maven
          cd /workspace/splitcells-net/
          git clone --depth 1 ssh://codeberg.org/splitcells-net/net.splitcells.network.bom.base.git
          git clone --depth 1 ssh://codeberg.org/splitcells-net/net.splitcells.network.bom.git
          git clone --depth 1 ssh://codeberg.org/splitcells-net/net.splitcells.network.git
      - name: Build
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd /workspace/splitcells-net/net.splitcells.network.bom.base
          mvn clean install
          cd /workspace/splitcells-net/net.splitcells.network.bom
          mvn clean install
          cd /workspace/splitcells-net/net.splitcells.network
          mvn -B clean install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=www-splitcells-net_net.splitcells.network -Dsonar.test.exclusions=src/main/java/** -Dsonar.organization=www-splitcells-net -Dsonar.host.url=https://sonarcloud.io # `-Dsonar.inclusions=src/main/**,bin/*` does not seem to work.