# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
# SPDX-FileCopyrightText: Contributors To The `net.splitcells.*` Projects
on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: alpine:latest
    steps:
      - run: |
          apk update
          apk add git python3 openjdk21-jdk maven
          echo All Good at $(pwd)