# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
# SPDX-FileCopyrightText: Contributors To The `net.splitcells.*` Projects
on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: alpine:latest
    steps:
      - run: |
          apk update # $(pwd) = /workspace/splitcells-net/net.splitcells.network
          apk add git python3 openjdk21-jdk maven
          cd ..
          git clone https://codeberg.org/splitcells-net/net.splitcells.network.bom.git
          cd ../net.splitcells.network.bom
          mvn clean install
          cd ../net.splitcells.network
          mvn -B clean install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=www-splitcells-net_net.splitcells.network -Dsonar.test.exclusions=src/main/java/** -Dsonar.organization=www-splitcells-net -Dsonar.host.url=https://sonarcloud.io # `-Dsonar.inclusions=src/main/**,bin/*` does not seem to work.
          bash <(curl -s https://codecov.io/bash) # Upload tests to codecov.io.