#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Minimize the number of dependencies as the context of this program is not known and is used for bootstrapping.
# TODO Remove this command in order to minimize source code size.
cd $1
mkdir -p ~/bin
	cp ./* ~/bin/
	chmod -R +x ~/bin/*
echo Commands at $1 installed.
