image: freebsd/latest
packages:
  - openjdk21
  - maven
  - python3
sources:
  - https://git.sr.ht/~splitcells-net/net.splitcells.network
  - https://git.sr.ht/~splitcells-net/net.splitcells.network.bom
tasks:
  - build: |
      cd net.splitcells.network.bom
      mvn clean install
      cd ../net.splitcells.network
      bin/build.part.with.java
triggers:
  - action: email
    condition: failure
    to: martins.avots@splitcells.net