# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
# SPDX-FileCopyrightText: Contributors To The `net.splitcells.*` Projects
FROM docker.io/eclipse-temurin:21-jdk-jammy
RUN apt update
RUN apt install --yes maven git python3
VOLUME /root/Documents/
VOLUME /root/.ssh/
VOLUME /root/.m2
