#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
import subprocess
import sys
if __name__ == '__main__':
	if not len(sys.argv) == 4 or not sys.argv[2] == 'times':
		subprocess.call(['echo.error', 'error'])
		sys.exit(1)
	print(sys.argv[1] * int(sys.argv[3]))
	sys.exit(0)