# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
# SPDX-FileCopyrightText: Contributors To The `net.splitcells.*` Projects
build :
	@echo Makefile is only present for compatibility and to ease the initial setup.
	@echo Tasks of the project are located in '"'./bin/*'"' and should be executed in the root folder of this project.
	@echo
	$(chmod +x ./bin/*)
	@echo Nothing has to be done in order to build this project.
	@echo You can just execute '"'make install'"'.
	@echo Sudo etc. is not required.
install :
	./bin/install
