.Dd 14/11/2020
.Dt user.configure
.Sh NAME
"user.configure": Configures the current user.
.Sh Description

Configures the current user.
The main difference to "package.install" is the fact,
that "user.configure" works without arguments and defines the configuration of the current user.
This command may or may not require extended rights.


It is preferred that every "user.configure" command calls a set of "package.install" commands.
This ensures the portability of user configurations.
It also makes it possible to install the same set of commands on multiple computers,
even if the computers require different configurations.
In this case the administrator has only to create the "~/.config/net.splitcells.os.state.interface/user.configure" command on each computer,
that defines which configurations are required for each computer.